trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: build
    displayName: Build and analyze
    jobs:
      - job: Build
        steps:

        - task: UseDotNet@2
          displayName: 'Use latest .NET Core SDK'
          inputs:
            packageType: 'sdk'
            version: '6.x'

        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: restore
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            command: 'build'
            projects: '**/*.sln'
            arguments: '/warnaserror /warn:5'

  - stage: test
    displayName: unit tests
    jobs:
      - job: Test
        steps:

        - task: DotNetCoreCLI@2
          displayName: 'dotnet test'
          inputs:
            command: 'test'
            projects: '**/*Tests.csproj'
            arguments: '/warnaserror /warn:5'
